2022-02-01 10:41:17,858 INFO    MainThread:1044 [internal.py:wandb_internal():87] W&B internal server running at pid: 1044, started at: 2022-02-01 10:41:17.858432
2022-02-01 10:41:17,862 INFO    WriterThread:1044 [datastore.py:open_for_write():77] open: /workspace/project/test/wandb/offline-run-20220201_104116-3jii1n6k/run-3jii1n6k.wandb
2022-02-01 10:41:17,864 DEBUG   HandlerThread:1044 [handler.py:handle_request():130] handle_request: run_start
2022-02-01 10:41:19,247 DEBUG   HandlerThread:1044 [meta.py:__init__():40] meta init
2022-02-01 10:41:19,248 DEBUG   HandlerThread:1044 [meta.py:__init__():54] meta init done
2022-02-01 10:41:19,248 DEBUG   HandlerThread:1044 [meta.py:probe():214] probe
2022-02-01 10:41:19,255 DEBUG   HandlerThread:1044 [meta.py:_setup_git():204] setup git
2022-02-01 10:41:19,289 DEBUG   HandlerThread:1044 [meta.py:_setup_git():211] setup git done
2022-02-01 10:41:19,289 DEBUG   HandlerThread:1044 [meta.py:_save_pip():58] save pip
2022-02-01 10:41:19,290 DEBUG   HandlerThread:1044 [meta.py:_save_pip():72] save pip done
2022-02-01 10:41:19,290 DEBUG   HandlerThread:1044 [meta.py:_save_conda():79] save conda
2022-02-01 10:41:19,820 DEBUG   HandlerThread:1044 [meta.py:_save_conda():89] save conda done
2022-02-01 10:41:19,821 DEBUG   HandlerThread:1044 [meta.py:probe():252] probe done
2022-02-01 13:34:37,942 WARNING MainThread:1044 [internal.py:wandb_internal():146] Internal process interrupt: 1
2022-02-01 13:34:40,593 WARNING MainThread:1044 [internal.py:wandb_internal():146] Internal process interrupt: 2
2022-02-01 13:34:40,593 ERROR   MainThread:1044 [internal.py:wandb_internal():149] Internal process interrupted.
2022-02-01 13:34:40,861 INFO    SenderThread:1044 [sender.py:finish():1070] shutting down sender
2022-02-01 13:34:41,284 INFO    WriterThread:1044 [datastore.py:close():281] close: /workspace/project/test/wandb/offline-run-20220201_104116-3jii1n6k/run-3jii1n6k.wandb
2022-02-01 13:34:41,308 INFO    HandlerThread:1044 [handler.py:finish():731] shutting down handler
2022-02-01 13:34:41,309 INFO    MainThread:1044 [internal.py:handle_exit():77] Internal process exited
